name: rodolffoUtils Reloaded
version: 1.0
authors: [Rodolffo, Zolli]
description: Various utilities for server admins. Rewrite by Zolli
main: com.zolli.rodolffoutilsreloaded.rodolffoUtilsReloaded
depend: [Vault]
commands:
  fakechat:
    aliases: [fc]
    description: Fakes a chat message
    usage: /<command> [name] [message]
  definebutton:
    description: Define a new special button
    usage: /<command> [type] [name]
  achat:
    aliases: [ac]
    description: Sends a message for online admins
    usage: /<command> [message]