name: rodolffoUtils Reloaded
version: 1.0
authors: [Rodolffo, Zolli]
description: Various utilities for server admins. Rewrite by Zolli
main: com.zolli.rodolffoutilsreloaded.rodolffoUtilsReloaded
depend: [Vault]
commands:
  fakechat:
    description: Fakes a chat message
    usage: /<command> name message
  achat:
    aliases: [ac]
    description: Sends a message for online admins
    usage: /<command> message