name: rodolffoUtils Reloaded
version: 1.2
authors: [Rodolffo, Zolli]
description: Various utilities for server admins. Rewrite by Zolli
main: com.zolli.rodolffoutilsreloaded.rodolffoUtilsReloaded
depend: [Vault]
commands:
  fakechat:
    aliases: [fc]
    description: Fakes a chat message
  definebutton:
    description: Define a new special button
  achat:
    aliases: [ac]
    description: Sends a message for online admins
  idban:
    description: Ban player UID
  idunban:
    description: Unban player UID
  napos:
    description: Make a sunny day
  nappal:
    description: Set the world time
  rur:
    description: Save or reload config
  fullenchant:
    description: Set the holding item all enchantment to max level
  entitylist:
    description: write the nearby entity's number
    aliases: [el]
